/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.team199.deepbluesim.gradle

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'org.team199.deepbluesim' plugin.
 */
class DeepBlueSimPluginTest extends Specification {
    def "plugin registers installDeepBlueSim task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("org.team199.deepbluesim")

        then:
        project.tasks.findByName("installDeepBlueSim") != null
    }

    def "plugin makes simulation tasks depend on DeepBlueSim"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("org.team199.deepbluesim") 
        project.plugins.apply("edu.wpi.first.GradleRIO")

        then:
        project.tasks.findByName('externalSimulate').taskDependencies.getDependencies().contains(project.tasks.findByName("installDeepBlueSim"))
    }
}
