/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.team199.deepbluesim.gradle

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'org.team199.deepbluesim' plugin.
 */
class DeepBlueSimPluginTest extends Specification {
    def "plugin registers greeting task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("org.team199.deepbluesim")

        then:
        project.tasks.findByName("greeting") != null
    }

    def "plugin registers installControllersAndProtos task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("org.team199.deepbluesim")

        then:
        project.tasks.findByName("installControllersAndProtos") != null
    }
}
