/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.team199.deepbluesim.gradle

import org.gradle.api.Project
import org.gradle.api.Plugin

import org.apache.commons.io.FileUtils
import org.apache.commons.io.IOUtils

/**
 * A simple 'hello world' plugin.
 */
class DeepBlueSimPlugin implements Plugin<Project> {
    void apply(Project project) {
        // Register a task
        project.tasks.register("greeting") {
            doLast {
                println("Hello from plugin 'org.team199.deepbluesim'")
            }
        }
        // project.task installControllersAndProtos(type: Copy) {
        //     from shadowJar.outputs
        //     into "example/Webots/controllers/${shadowJar.archiveBaseName.get()}"
        // }

        project.tasks.register("installControllersAndProtos") {
            doLast {
                def resourceStream = DeepBlueSimPlugin.class.getResourceAsStream("Webots.zip")
                if (resourceStream == null) throw new RuntimeException("resourceStream is null")
                def dbsDir = new File(project.buildDir, "tmp/deepbluesim")
                dbsDir.mkdirs()
                FileUtils.copyInputStreamToFile(resourceStream, new File(dbsDir,"Webots.zip"))

            }
        }
    }
}
