name: 'Run System Test'
description: 'Runs the system test'
runs:
  using: 'composite'
  steps:
    - name: Assemble the controller and copy it to the example
      run: |
        ./gradlew copyJarToExample --info --stacktrace
      shell: bash

    - name: Start Webots
      run: |
        $RUN_WEBOTS ./example/Webots/worlds/Test.wbt &> webots-${{ runner.os }}.log &
      shell: bash

    - name: Do the system test
      run: |
        ./gradlew build --info --stacktrace
      shell: bash
