name: 'Run System Test'
description: 'Runs the system test'
inputs:
  webotsWaitSecs:
    description: "How many seconds to wait for Webots to start before starting the robot code"
    required: false
    default: 0
runs:
  using: 'composite'
  steps:
    - name: Assemble the controller and copy it to the example
      run: |
        ./gradlew copyJarToExample --info --stacktrace
      shell: bash

    - name: Start Webots
      run: |
        $RUN_WEBOTS ./example/Webots/worlds/Test.wbt &> webots-${{ runner.os }}.log &
        echo "Sleeping for ${{ inputs.webotsWaitSecs }} secs"
        sleep ${{ inputs.webotsWaitSecs }}
        echo "Done sleeping"
      shell: bash

    - name: Do the system test
      run: |
        ./gradlew build --info --stacktrace
      shell: bash
