# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy: 
      matrix:
        os: [ macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Webots (ubuntu-latest)
      if: matrix.os == 'ubuntu-latest'
      run: |
        curl -L -O https://github.com/cyberbotics/webots/releases/download/R2021a/webots_2021a_amd64.deb
        sudo apt install ./webots_2021a_amd64.deb

    - name: Install Webots (macos-latest)
      if: matrix.os == 'macos-latest'
      run: |
        curl -L -O https://github.com/cyberbotics/webots/releases/download/R2021a-rev1/webots-R2021a-rev1.dmg
        mkdir ~/Applications
        mkdir ~/Mount
        hdiutil attach webots-R2021a-rev1.dmg -mountpoint ~/Mount
        echo "Contents of ~/Mount:"
        ls ~/Mount
        echo "Copying to ~/Applications"
        cp -r ~/Mount/Webots.app ~/Applications
        hdiutil detach ~/Mount
        rmdir ~/Mount

    - name: Checkout the code recursively
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Gradle
      run: ./gradlew build
