# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI on MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy: 
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            webotsPkg: "webots-R2021a.dmg"
            webotsUrl: [ "https://github.com/cyberbotics/webots/releases/download/R2021a/" ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache Webots install
      id: cache-webots-install
      if: matrix.os == 'macos-latest'
      uses: actions/cache@v2
      with:
        path: ~/Applications
        key: webots-v2021a-install-${{ matrix.webotsPkg }}

    - name: Download and Install Webots
      if: steps.cache-webots-install.outputs.cache-hit != 'true'
      run: |
        curl -L -O ${{ format('{0}{1}', matrix.webotsUrl, matrix.webotsPkg) }}
        mkdir ~/Mount
        mkdir -p ~/Applications
        hdiutil attach ${{ matrix.webotsPkg }} -mountpoint ~/Mount
        cp -R ~/Mount/Webots.app ~/Applications
        hdiutil detach ~/Mount
        rmdir ~/Mount

    - name: Assemble the controller and copy it to the example
      run: |
        ./gradlew copyJarToExample --info --stacktrace
      shell: bash

    - name: Archive the example folder for diagnositic purposes
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: example
        path: example/

    - name: Start Webots
      run: |
        export LIBGL_ALWAYS_SOFTWARE=true
        export WEBOTS_DISABLE_SAVE_SCREEN_PERSPECTIVE_ON_CLOSE=true
        export HALSIMWS_HOST=127.0.0.1
        ~/Applications/Webots.app/webots --no-sandbox --no-rendering --stdout --stderr --minimize --batch --mode=realtime ./example/Webots/worlds/Test.wbt &> webots-${{ matrix.os }}.log &
        echo "Sleeping for 10 minutes(!) waiting for webots to start"
        sleep 600
        echo "Done sleeping"
        jobs

    - name: Do the system test
      run: |
        ./gradlew build --info --stacktrace
      shell: bash

    - name: Archive Webots log
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Webots log for ${{ matrix.os }}
        path: webots-${{ matrix.os }}.log
